<template>
  <view class="box">
    <view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-align:center"><text style="color:#333333; font-family:微软雅黑; font-size:18pt; font-weight:bold">雄登康平台服务协议</text><text style="color:#333333; font-family:微软雅黑; font-size:9pt">&#xa0;</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:宋体; font-size:9pt">&#xa0;</text><text style="color:#333333; font-family:宋体; font-size:9pt"> </text><text style="color:#333333; font-family:宋体; font-size:9pt">&#xa0;</text><text style="color:#333333; font-family:宋体; font-size:9pt"> </text><text style="color:#333333; font-family:宋体; font-size:9pt">&#xa0;</text><text style="color:#333333; font-family:宋体; font-size:9pt"> </text><text style="color:#333333; font-family:宋体; font-size:9pt">&#xa0;</text><text style="color:#333333; font-family:宋体; font-size:9pt"> </text><text style="color:#333333; font-family:宋体; font-size:9pt">&#xa0;</text><text style="color:#333333; font-family:宋体; font-size:9pt"> </text><text style="color:#333333; font-family:宋体; font-size:9pt">&#xa0;</text><text style="color:#333333; font-family:宋体; font-size:9pt"> </text><text style="color:#333333; font-family:宋体; font-size:9pt">&#xa0;</text><text style="color:#333333; font-family:宋体; font-size:9pt"> </text><text style="color:#333333; font-family:宋体; font-size:9pt">&#xa0;</text><text style="color:#333333; font-family:宋体; font-size:9pt"> </text><text style="color:#333333; font-family:宋体; font-size:9pt">&#xa0;</text><text style="color:#333333; font-family:宋体; font-size:9pt"> </text><text style="color:#333333; font-family:宋体; font-size:9pt">&#xa0;</text><text style="color:#333333; font-family:宋体; font-size:9pt"> </text><text style="color:#333333; font-family:宋体; font-size:9pt">&#xa0;</text><text style="color:#333333; font-family:宋体; font-size:9pt"> </text><text style="color:#333333; font-family:宋体; font-size:9pt">&#xa0;</text><text style="color:#333333; font-family:宋体; font-size:9pt"> </text><text style="color:#333333; font-family:宋体; font-size:9pt">&#xa0;</text><text style="color:#333333; font-family:宋体; font-size:9pt"> </text><text style="color:#333333; font-family:宋体; font-size:9pt">&#xa0;</text><text style="color:#333333; font-family:宋体; font-size:9pt"> </text><text style="color:#333333; font-family:宋体; font-size:9pt">&#xa0;</text><text style="color:#333333; font-family:宋体; font-size:9pt"> </text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:178.5pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">最新版本生效日期：2020年05月</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">11</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">日</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">提示条款</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">欢迎您与雄登康公司签署本《雄登康平台服务协议》（下称“本协议”）并使用雄登康平台服务！</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal; text-decoration:none">&#xa0;</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal; text-decoration:none">   </text><text style="font-family:微软雅黑; font-size:12pt; font-weight:normal; text-decoration:none">本协议为《雄登康</text><text style="font-family:微软雅黑; font-size:12pt; font-weight:normal; text-decoration:none">平台</text><text style="font-family:微软雅黑; font-size:12pt; font-weight:normal; text-decoration:none">服务协议》修订版本，自本协议发布之日起，雄登康平台各处所称“雄登康</text><text style="font-family:微软雅黑; font-size:12pt; font-weight:normal; text-decoration:none">平台</text><text style="font-family:微软雅黑; font-size:12pt; font-weight:normal; text-decoration:none">服务协议”均指本协议。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">各服务条款前所列索引关键词仅为帮助您理解该条款表达的主旨之用，不影响或限制本协议条款的含义或解释。为维护您自身权益，建议您仔细阅读各条款具体表述。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">&#xa0;</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">  </text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">【审慎阅读】</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">您在申请注册流程中点击同意本协议之前，应当认真阅读本协议。</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">请您务必审慎阅读、充分理解各条款内容，特别是免除或者限制责任的条款、法律适用和争议解决条款。免除或者限制责任的条款将以粗体下划线标识，您应重点阅读。</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">如您对协议有任何疑问，可向雄登康平台客服咨询。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal">&#xa0;</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal">  </text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">【签约动作】</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal">当您按照注册页面提示填写信息、阅读并同意本协议且完成全部注册程序后，即表示您已充分阅读、理解并接受本协议的全部内容，并与雄登康达成一致，成为雄登康平台“用户”。</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">阅读本协议的过程中，如果您不同意本协议或其中任何条款约定，您应立即停止注册程序。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">&#xa0;</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt 3.75pt 3.55pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">一、</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">定义</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt 3.75pt 3.55pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">雄登康平台</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">：指包括雄登康网站及客户端。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt 3.75pt 3.55pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">：雄登康平台经营者的单称或合称，</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">包括</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">雄登康经营者诸暨市雄登康网络科技有限公司。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">雄登康平台服务</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">：雄登康基于互联网，以包含雄登康平台网站、客户端等在内的各种形态（包括未来技术发展出现的新的服务形态）向您提供的各项服务。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">雄登康平台规则</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">：包括在所有雄登康平台规则频道内已经发布及后续发布的全部规则、解读、公告等内容以及各平台在帮派、论坛、帮助中心内发布的各类规则、实施细则、产品流程说明、公告等。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">二、协议范围</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">2.1</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">&#xa0;</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">签约主体</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">&#xa0;</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">  </text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">【平等主体】</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">本协议由您与雄登康平台经营者共同缔结，本协议对您与雄登康平台经营者均具有合同效力。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal">&#xa0;</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal">  </text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">【主体信息】</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal">雄登康平台经营者是指经营雄登康平台的各法律主体，您可随时查看雄登康平台各网站首页底部公示的证照信息以确定与您履约的雄登康主体。本协议项下，</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">雄登康平台经营者可能根据雄登康平台的业务调整而发生变更，变更后的雄登康平台经营者与您共同履行本协议并向您提供服务，雄登康平台经营者的变更不会影响您本协议项下的权益。雄登康平台经营者还有可能因为提供新的雄登康平台服务而新增，如您使用新增的雄登康平台服务的，视为您同意新增的雄登康平台经营者与您共同履行本协议。发生争议时，您可根据您具体使用的服务及对您权益产生影响的具体行为对象确定与您履约的主体及争议相对方。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">2.2 补充协议</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal">由于互联网高速发展，您与雄登康签署的本协议列明的条款并不能完整罗列并覆盖您与雄登康所有权利与义务，现有的约定也不能保证完全符合未来发展的需求。因此，</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">雄登康平台法律声明及</text><text style="font-family:微软雅黑; font-size:12pt; font-weight:bold">隐私权政策</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">、雄登康平台规则均为本协议的补充协议，与本协议不可分割且具有同等法律效力。如您使用雄登康平台服务，视为您同意上述补充协议。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">&#xa0;</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">三、账户注册与使用</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">3.1</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">&#xa0;</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">用户资格</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">您确认，在您开始注册程序使用雄登康平台服务前，您应当具备中华人民共和国法律规定的与您行为相适应的民事行为能力。</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">若您不具备前述与您行为相适应的民事行为能力，则您及您的监护人应依照法律规定承担因此而导致的一切后果。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal">此外，您还需确保您不是任何国家、地区或国际组织实施的贸易限制、经济制裁或其他法律法规限制的对象，也未直接或间接为前述对象提供资金、商品或服务，</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal; text-decoration:underline">否则您应当停止使用</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal; text-decoration:underline">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal; text-decoration:underline">平台服务，同时您理解违反前述要求可能会造成您无法正常注册及使用</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal; text-decoration:underline">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal; text-decoration:underline">平台服务。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">3.2</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">&#xa0;</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">账户说明</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">&#xa0;</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">  </text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">【账户获得】</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">当您按照注册页面提示填写信息、阅读并同意本协议且完成全部注册程序后，您可获得雄登康平台账户并成为雄登康平台用户。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">雄登康平台只允许每位用户使用一个雄登康平台账户。如有证据证明或雄登康根据雄登康平台规则判断您存在不当注册或不当使用多个雄登康平台账户的情形，雄登康平台可采取冻结或关闭账户、取消订单、拒绝提供服务等措施，如给雄登康平台及相关方造成损失的，您还应承担赔偿责任。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">【账户使用】</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">您有权使用您设置或确认的雄登康会员名、邮箱、手机号码（以下简称“账户名称”）及您设置的密码（账户名称及密码合称“账户”）登录雄登康平台。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">您有权使用您的雄登康平台账户登录雄登康平台的其他平台。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">由于您的雄登康平台账户关联您的个人信息及雄登康平台商业信息，您的雄登康平台账户仅限您本人使用。未经雄登康平台同意，您直接或间接授权第三方使用您雄登康平台账户或获取您账户项下信息的行为无效。如雄登康根据雄登康平台规则中约定的违约认定程序及标准判断您雄登康平台账户的使用可能危及您的账户安全及/或雄登康平台信息安全的，雄登康平台可拒绝提供相应服务或终止本协议。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">【账户转让】</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal">由于用户账户关联用户信用信息，仅当有法律明文规定、司法裁定或经雄登康同意，并符合雄登康平台规则规定的用户账户转让流程的情况下，您可进行账户的转让。您的账户一经转让，该账户项下权利义务一并转移。</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">除此外，您的账户不得以任何方式转让，否则</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">平台有权追究您的违约责任，且由此产生的责任及后果均由您自行承担。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">【实名认证】</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">作为雄登康平台经营者，为使您更好地使用雄登康平台的各项服务，保障您的账户安全，雄登康可要求您按支付宝等第三方金融支付公司要求及相关法律法规规定完成实名认证。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">【不活跃账户回收】如您的账户同时符合以下条件，则</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">可回收您的账户。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">（一）未绑定通过实名认证</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">（二）连续六个月未用于登录</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">（三）不存在未到期的有效业务。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">3.3</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">&#xa0;</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">注册信息管理</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">3.3.1</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">&#xa0;</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">真实合法</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">【信息真实】</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">在使用雄登康平台服务时，您应当按雄登康平台页面的提示准确完整地提供您的信息（包括您的姓名及电子邮件地址、联系电话、联系地址等），以便雄登康或其他用户与您联系。</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">您了解并同意，您有义务保持您提供信息的真实性及有效性。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21.55pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">【会员名的合法性】您设置的</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">会员名不得违反国家法律法规及</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">平台相关规则关于会员名的管理规定，否则</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">可回收您的雄登康会员名。</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">雄登康会员名的回收不影响您以邮箱、手机号码登录雄登康平台并使用雄登康平台服务。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21.55pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">3.3.2</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">&#xa0;</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">更新维护</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">您应当及时更新您提供的信息，在法律有明确规定要求雄登康作为平台服务提供者必须对部分用户（如平台卖家等）的信息进行核实的情况下，雄登康将依法不时地对您的信息进行检查核实，您应当配合提供最新、真实、完整、有效的信息。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">如</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">按您最后一次提供的信息与您联系未果、您未按</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">的要求及时提供信息、您提供的信息存在明显不实或行政司法机关核实您提供的信息无效的，您将承担因此对您自身、他人及</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">造成的全部损失与不利后果。</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">可向您发出询问或要求整改的通知，并要求您进行重新认证，直至中止、终止对您提供部分或全部</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">平台服务，</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">对此不承担责任。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">3.4</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">&#xa0;</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">账户安全规范</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">【账户安全保管义务】</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">您的账户为您自行设置并由您保管，雄登康任何时候均不会主动要求您提供您的账户密码。因此，建议您务必保管好您的账户，并确保您在每个上网时段结束时退出登录并以正确步骤离开雄登康平台。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">账户因您主动泄露或因您遭受他人攻击、诈骗等行为导致的损失及后果，</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">并不承担责任，您应通过司法、行政等救济途径向侵权行为人追偿。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">&#xa0;</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">   </text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">【账户行为责任自负】</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">除雄登康存在过错外，</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">您应对您账户项下的所有行为结果（包括但不限于在线签署各类协议、发布信息、购买商品及服务及披露信息等）负责。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21.55pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">【日常维护须知】</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal">如发现任何未经授权使用您账户登录雄登康平台或其他可能导致您账户遭窃、遗失的情况，建议您立即通知雄登康，并授权雄登康将该信息同步后台。</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">您理解</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">对您的任何请求采取行动均需要合理时间，且</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">应您请求而采取的行动可能无法避免或阻止侵害后果的形成或扩大，除</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">存在法定过错外，</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">不承担责任。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21.55pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">&#xa0;</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21.55pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">四、</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">平台服务及规范</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21.55pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">【服务概况】</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">您有权在雄登康平台上享受商品及/或服务的浏览、收藏、购买与评价、交易争议处理、信息交流如问答及分享等服务。雄登康提供的服务内容众多，具体您可登录雄登康平台浏览。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21.55pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">4.1</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">&#xa0;</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">商品及/或服务的浏览、收藏</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">在您浏览我们网站或客户端的过程中，雄登康为您提供了信息分类、关键词检索、筛选、收藏及关注等功能，以更好地匹配您的需求。您可以对您感兴趣的商品及/或服务进行收藏、添加至购物车，品牌等。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">&#xa0;</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">&#xa0;</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">  </text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">4.2商品及/或服务的购买与评价</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">&#xa0;</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">  </text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">【商品及/或服务的购买】</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">当您在雄登康平台购买商品及/或服务时，请您务必仔细确认所购商品的品名、价格、数量、型号、规格、尺寸或服务的时间、内容、限制性要求等重要事项，并在下单时核实您的联系地址、电话、收货人等信息。</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">如您填写的收货人非您本人，则该收货人的行为和意思表示产生的法律后果均由您承担。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">您的购买行为应当基于真实的消费需求，不得存在对商品及/或服务实施恶意购买、恶意维权等扰乱雄登康平台正常交易秩序的行为。基于维护雄登康平台交易秩序及交易安全的需要，雄登康发现上述情形时可主动执行关闭相关交易订单等操作。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">【C</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">2C/CPC</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">交易】</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">雄登康平台存在“C</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">2C</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">”和“C</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">PC</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">”两种出价形式。</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">&#xa0;</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">【评价】</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">您有权在雄登康平台提供的评价系统中对与您达成交易的其他用户商品及/或服务进行评价。您应当理解，您在雄登康平台的评价信息是公开的，如您不愿意在评价信息中向公众披露您的身份信息，您有权选择通过匿名形式发表评价内容。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal">为确保评价内容能为消费者购物决策提供可靠的依据，反映商品及/或服务的真实情况，您的所有评价行为应遵守雄登康平台规则的相关规定，评价内容应当合法、客观、真实，与交易的商品及/或服务具有关联性，且不应包含任何污言秽语、色情低俗、广告信息及法律法规与本协议列明的其他禁止性信息；您不应以不正当方式帮助他人提升信用或利用评价权利对其他用户实施威胁、敲诈勒索。雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">可按照</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">平台规则的相关规定对您实施上述行为所产生的评价信息采取必要处置措施。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">4.3交易争议处理</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">【交易争议处理途径】</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">您在雄登康平台交易过程中与其他用户发生争议的，您或其他用户中任何一方均有权选择以下途径解决：</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">（一）与争议相对方自主协商；</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">（二）使用雄登康平台提供的争议调处服务；</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">（三）请求消费者协会或者其他依法成立的调解组织调解；</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">（四）向有关行政部门投诉；</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">（五）根据与争议相对方达成的仲裁协议（如有）提请仲裁机构仲裁；</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">（六）向人民法院提起诉讼。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">【平台调处服务】</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal">如您依据雄登康平台规则使用雄登康平台的争议调处服务，则表示您认可并愿意履行雄登康平台的客服或大众评审员（“调处方”）作为独立的第三方根据其所了解到的争议事实并依据雄登康平台规则所作出的调处决定（包括调整相关订单的交易状态、判定将争议款项的全部或部分支付给交易一方或双方等）。在雄登康平台调处决定作出前，您可选择上述（三）、（四）、（五）、（六）途径（下称“其他争议处理途径”）解决争议以中止雄登康平台的争议调处服务。</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">如您对调处决定不满意，您仍有权采取其他争议处理途径解决争议，但通过其他争议处理途径未取得终局决定前，您仍应先履行调处决定。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">4.4</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">&#xa0;</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">信息交流</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">为满足用户间分享购物心得等信息交流需求，您可通过雄登康提供的问答、晒单分享、论坛、群组及其他信息发布功能公开发布信息及与其他用户互动，信息的形式包括文字、图片、视频、直播内容等，您须确保您所发布的所有信息均符合相关法律法规及本协议的要求。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">4.5</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">&#xa0;</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">贸易限制</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal">针对通过雄登康平台取得的商品、服务、软件及技术（包括雄登康平台提供的软件及技术），您承诺遵守所有适用的进出口管制、贸易限制与经济制裁相关法律法规。基于维护雄登康平台交易秩序及交易安全的需要，如您违反前述承诺的，雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">可在发现上述情形时主动执行关闭相关交易订单及作出账户处置等操作。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">4.6 费用</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">雄登康为雄登康平台向您提供的服务付出了大量的成本，除雄登康平台明示的收费业务外，雄登康向您提供的服务目前是免费的。如未来雄登康向您收取合理费用，雄登康会采取合理途径并以足够合理的期限提前通过本协议第八条约定的方式通知您，确保您有充分选择的权利。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">4.7 责任限制</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">【不可抗力及第三方原因】</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">依照法律规定履行基础保障义务，但对于下述原因导致的合同履行障碍、履行瑕疵、履行延后或履行内容变更等情形，</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">并不承担相应的违约责任：</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">（一）因自然灾害、罢工、暴乱、战争、政府行为、司法行政命令等不可抗力因素；</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">（二）因电力供应故障、通讯网络故障等公共服务因素或第三人因素；</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">（三）在</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">已尽善意管理的情况下，因常规或紧急的设备与系统维护、设备与系统故障、网络信息与数据安全等因素</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">【海量信息】</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal">雄登康仅向您提供雄登康平台服务，您了解雄登康平台上的信息系用户自行发布，且可能存在风险和瑕疵。雄登康将通过依法建立相关检查监控制度尽可能保障您在雄登康平台上的合法权益及良好体验。同时，</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">鉴于</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">平台具备存在海量信息及信息网络环境下信息与实物相分离的特点，</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">无法逐一审查商品及/或服务的信息，无法逐一审查交易所涉及的商品及/或服务的质量、安全以及合法性、真实性、准确性，对此您应谨慎判断</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">【调处决定】</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal">您理解并同意，在争议调处服务中，雄登康平台的客服、大众评审员并非专业人士，仅能以普通人的认知对用户提交的凭证进行判断。因此，</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">除存在故意或重大过失外，调处方对争议调处决定免责。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">&#xa0;</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">5、</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">用户信息的保护及授权</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">5.1 个人信息的保护</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">雄登康非常重视用户个人信息（即能够独立或与其他信息结合后识别用户身份的信息）的保护，在您使用雄登康提供的服务时，您同意雄登康按照在雄登康平台上公布的隐私权政策收集、存储、使用、披露和保护您的个人信息。</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">如客户端未设独立隐私权政策但使用了</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">平台账号登陆相应网站或客户端的，为保护您的隐私权，我们将参照适用</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">网隐私权政策的要求对您的个人信息进行收集、存储、使用、披露和保护。</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">雄登康希望通过隐私权政策向您清楚地介绍雄登康对您个人信息的处理方式，因此雄登康建议您完整地阅读隐私权政策，以帮助您更好地保护您的隐私权。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">5.2非个人信息的保证与授权</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">【信息的发布】</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">您声明并保证，您对您所发布的信息拥有相应、合法的权利。否则，雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">可对您发布的信息依法或依本协议进行删除或屏蔽。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">【禁止性信息】您应当确保您所发布的信息不包含以下内容：</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">（一）违反国家法律法规禁止性规定的；</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">（二）政治宣传、封建迷信、淫秽、色情、赌博、暴力、恐怖或者教唆犯罪的；</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">（三）欺诈、虚假、不准确或存在误导性的；</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">（四）侵犯他人知识产权或涉及第三方商业秘密及其他专有权利的；</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">（五）侮辱、诽谤、恐吓、涉及他人隐私等侵害他人合法权益的；</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">（六）存在可能破坏、篡改、删除、影响</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">平台任何系统正常运行或未经授权秘密获取</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">平台及其他用户的数据、个人资料的病毒、木马、爬虫等恶意软件、程序代码的；</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">（七）其他违背社会公共利益或公共道德或依据相关</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">平台协议、规则的规定不适合在</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">平台上发布的。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">【授权使用】</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">对于您提供、发布及在使用雄登康平台服务中形成的除个人信息外的文字、图片、视频、音频等非个人信息，均不会因上传、发布等行为发生知识产权、肖像权等权利的转移。除非我们另行说明，</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">在法律允许的范围内，您免费授予</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">及其关联公司、支付宝公司非排他的、无地域限制的许可使用（包括存储、使用、复制、修订、编辑、发布、展示、翻译、分发上述信息或制作派生作品，以已知或日后开发的形式、媒体或技术将上述信息纳入其它作品内等）及可再许可第三方使用的权利，以及可以自身名义对第三方侵权行为取证及提起诉讼的权利。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">您授权</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">将您在账户注册和使用</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">平台服务过程中提供、形成的信息传递给后台等其他相关服务提供者。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">&#xa0;</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">六、 用户的违约及处理</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">&#xa0;</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">6.1</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">&#xa0;</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">违约认定</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">发生如下情形之一的，视为您违约：</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">（一）使用雄登康平台服务时违反有关法律法规规定的；</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">（二）违反本协议或本协议补充协议（即本协议第2.2条）约定的。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">为适应电子商务发展和满足海量用户对高效优质服务的需求，您理解并同意，雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">可在</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">平台规则中约定违约认定的程序和标准。如：</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">可依据您的用户数据与海量用户数据的关系来认定您是否构成违约；您有义务对您的数据异常现象进行充分举证和合理解释，否则将被认定为违约。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">6.2</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">&#xa0;</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">违约处理措施</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">【信息处理】</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal">您在雄登康平台上发布的信息构成违约的，雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">可根据相应规则立即对相应信息进行删除、屏蔽处理。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">【行为限制】</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal">您在雄登康平台上实施的行为，或虽未在雄登康平台上实施但对雄登康平台及其用户产生影响的行为构成违约的，雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">可依据相应规则对您执行账户扣分、中止向您提供部分或全部服务、划扣违约金等处理措施。如您的行为构成根本违约的，</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">可查封您的账户，终止向您提供服务。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">【支付账户处理】</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal">当您违约的同时存在欺诈、售假、盗用他人账户等特定情形或您存在危及他人交易安全或账户安全风险时，雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">会依照您行为的风险程度指示支付公司对您的支付账户采取取消收款、资金止付等强制措施。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">【处理结果公示】</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">可将对您上述违约行为处理措施信息以及其他经国家行政或司法机关生效法律文书确认的违法信息在</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">平台上予以公示。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal">&#xa0;</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">6.3 赔偿责任</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">如您的行为使</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">及/或其关联公司、支付公司遭受损失（包括自身的直接经济损失、商誉损失及对外支付的赔偿金、和解款、律师费、诉讼费等间接经济损失），您应赔偿雄登康及/或其关联公司、支付公司的上述全部损失。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">如您的行为使</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">及/或其关联公司、支付公司遭受第三人主张权利，</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">及/或其关联公司、支付公司可在对第三人承担金钱给付等义务后就全部损失向您追偿。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">如因您的行为使得第三人遭受损失或您怠于履行调处决定、</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">及/或其关联公司出于社会公共利益保护目的，可指示支付公司自您的支付账户中划扣相应款项进行支付。如您的支付余额或保证金不足以支付相应款项的，您同意委托</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">使用自有资金代您支付上述款项，您应当返还该部分费用并赔偿因此造成</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">的全部损失。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">您同意</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">指示支付公司自您的支付账户中划扣相应款项支付上述赔偿款项。如您支付账户中的款项不足以支付上述赔偿款项的，</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">及/或关联公司可直接抵减您在</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">及/或其关联公司其它协议项下的权益，并可继续追偿。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">6.4 特别约定</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">【商业贿赂】</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">如您向雄登康及/或其关联公司的雇员或顾问等提供实物、现金、现金等价物、劳务、旅游等价值明显超出正常商务洽谈范畴的利益，则可视为您存在商业贿赂行为。</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">发生上述情形的，</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">可立即终止与您的所有合作并向您收取违约金及/或赔偿金</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">，该等金额以雄登康因您的贿赂行为而遭受的经济损失和商誉损失作为计算依据。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">【关联处理】如您因严重违约导致</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">终止本协议时，出于维护平台秩序及保护消费者权益的目的，</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">及/或其关联公司可对与您在其他协议项下的合作采取中止甚或终止协议的措施，并以本协议第八条约定的方式通知您。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">如</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">与您签署的其他协议及</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">及/或其关联公司、支付公司与您签署的协议中明确约定了对您在本协议项下合作进行关联处理的情形，则</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">出于维护平台秩序的目的，可在收到指令时中止甚至终止协议，并以本协议第八条约定的方式通知您。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:宋体; font-size:9pt">&#xa0;</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt 3.75pt 21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">七、</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">协议的变更</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">雄登康可根据国家法律法规变化及维护交易秩序、保护消费者权益需要，不时修改本协议、补充协议，变更后的协议、补充协议（下称“变更事项”）将通过法定程序并以本协议第八条约定的方式通知您。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">如您不同意变更事项，您有权于变更事项确定的生效日前联系雄登康反馈意见。如反馈意见得以采纳，雄登康将酌情调整变更事项。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">如您对已生效的变更事项仍不同意的，您应当于变更事项确定的生效之日起停止使用</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">平台服务，变更事项对您不产生效力；如您在变更事项生效后仍继续使用</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">平台服务，则视为您同意已生效的变更事项。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">&#xa0;</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt 3.75pt 21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">八、</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">通知</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt 3.75pt 21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">8.1有效联系方式</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">您在注册成为雄登康平台用户，并接受雄登康平台服务时，您应该向雄登康提供真实有效的联系方式（包括您的电子邮件地址、联系电话、联系地址等），对于联系方式发生变更的，您有义务及时更新有关信息，并保持可被联系的状态。您在注册雄登康平台用户时生成的用于登陆雄登康平台接收站内信、系统消息</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">等</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">的会员账号（包括子账号），也作为您的有效联系方式。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">将向您的上述联系方式的其中之一或其中若干向您送达各类通知，而此类通知的内容可能对您的权利义务产生重大的有利或不利影响，请您务必及时关注。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal">您有权通过您注册时填写的手机号码或者电子邮箱获取您感兴趣的商品广告信息、促销优惠等商业性信息；</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">您如果不愿意接收此类信息，您有权通过</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">提供的相应的退订功能进行退订。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">8.2</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">&#xa0;</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">通知的送达</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">雄登康通过上述联系方式向您发出通知，其中以电子的方式发出的书面通知，包括但不限于在雄登康平台公告，向您提供的联系电话发送手机短信，向您提供的电子邮件地址发送电子邮件，向您的账号发送</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">聊天</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">信息、系统消息以及站内信信息，在发送成功后即视为送达；以纸质载体发出的书面通知，按照提供联系地址交邮后的第五个自然日即视为送达。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">对于在雄登康平台上因交易活动引起的任何纠纷，您同意司法机关（包括但不限于人民法院）可以通过手机短信、电子邮件等现代通讯方式或邮寄方式向您送达法律文书（包括但不限于诉讼文书）。您指定接收法律文书的手机号码、电子邮箱等联系方式为您在雄登康平台注册、更新时提供的手机号码、电子邮箱联系方式，司法机关向上述联系方式发出法律文书即视为送达。您指定的邮寄地址为您的法定联系地址或您提供的有效联系地址。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">您同意司法机关可采取以上一种或多种送达方式向您达法律文书，司法机关采取多种方式向您送达法律文书，送达时间以上述送达方式中最先送达的为准。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">您同意上述送达方式适用于各个司法程序阶段。如进入诉讼程序的，包括但不限于一审、二审、再审、执行以及督促程序等。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">你应当保证所提供的联系方式是准确、有效的，并进行实时更新。如果因提供的联系方式不确切，或不及时告知变更后的联系方式，使法律文书无法送达或未及时送达，由您自行承担由此可能产生的法律后果。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">&#xa0;</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt 3.75pt 21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">九、</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">协议的终止</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt 3.75pt 21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">9.1</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">&#xa0;</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">终止的情形</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt 3.75pt 21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">【用户发起的终止】</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">您有权通过以下任一方式终止本协议：</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">（一）在满足雄登康平台公示的</text><text style="font-family:微软雅黑; font-size:12pt">账户注销条件</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">时您通过</text><text style="font-family:微软雅黑; font-size:12pt">网站自助服务</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">注销您的账户的；</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">（二）变更事项生效前您停止使用并明示不愿接受变更事项的；</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">（三）您明示不愿继续使用雄登康平台服务，且符合雄登康平台终止条件的。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">&#xa0;</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">   </text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">【</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">发起的终止】</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">出现以下情况时，雄登康可以本协议第八条的所列的方式通知您终止本协议：</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">（一）您违反本协议约定，雄登康依据违约条款终止本协议的；</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">（二）您盗用他人账户、发布违禁信息、骗取他人财物、售假、扰乱市场秩序、采取不正当手段谋利等行为，雄登康依据雄登康平台规则对您的账户予以查封的；</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">（三）除上述情形外，因您多次违反雄登康平台规则相关规定且情节严重，雄登康依据雄登康平台规则对您的账户予以查封的；</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">（四）您的账户被雄登康依据本协议回收的；</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">（五）您在支付公司或雄登康平台有欺诈、发布或销售假冒伪劣/侵权商品、侵犯他人合法权益或其他严重违法违约行为的；</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">（六）其它应当终止服务的情况。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">9.2</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">&#xa0;</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">协议终止后的处理</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">&#xa0;</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">   </text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">【用户信息披露】本协议终止后，除法律有明确规定外，雄登康无义务向您或您指定的第三方披露您账户中的任何信息。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">&#xa0;</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">   </text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">【</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">权利】</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">本协议终止后，雄登康仍享有下列权利：</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">（一）继续保存您留存于雄登康平台的本协议第五条所列的各类信息；</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">（二）对于您过往的违约行为，雄登康仍可依据本协议向您追究违约责任。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">【交易处理】本协议终止后，对于您在本协议存续期间产生的交易订单，</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:normal">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">可通知交易相对方并根据交易相对方的意愿决定是否关闭该等交易订单；如交易相对方要求继续履行的，则您应当就该等交易订单继续履行本协议及交易订单的约定，并承担因此产生的任何损失或增加的任何费用。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">&#xa0;</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt; text-indent:21pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">十、法律适用、管辖与其他</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">&#xa0;</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">   </text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">【法律适用】本协议之订立、生效、解释、修订、补充、终止、执行与争议解决均适用中华人民共和国大陆地区法律；如法律无相关规定的，参照商业惯例及/或行业惯例。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">&#xa0;</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">  </text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">【管辖】您因使用</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">平台服务所产生及与</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">平台服务有关的争议，由</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">雄登康</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">与您协商解决。协商不成时，任何一方均可向被告所在地有管辖权的人民法院提起诉讼。</text></view>
      <view style="background-color:#ffffff; line-height:22pt; margin:3.75pt 0pt"><text style="color:#333333; font-family:微软雅黑; font-size:12pt">&#xa0;</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">  </text><text style="color:#333333; font-family:微软雅黑; font-size:12pt; font-weight:bold">【可分性】</text><text style="color:#333333; font-family:微软雅黑; font-size:12pt">本协议任一条款被视为废止、无效或不可执行，该条应视为可分的且并不影响本协议其余条款的有效性及可执行性。</text></view>
    </view>
  </view>
</template>

<script>
export default {
  data() {
    return {

    };
  }
}
</script>

<style lang="scss">
.box {
  padding: 30rpx;
}
</style>
